spring.application.name=Apex_Backend

spring.datasource.url=jdbc:mysql://localhost:3306/Apex_Motors?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Becca2025!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa,generate-ddl=true

logging.level.org.hibernate.SQL = DEBUG

server.port=3000
